name: octopus_g
description: Octopus G - Transform your resume into a stunning portfolio website with AI.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  skeletonizer: ^2.1.1
  file_picker: ^8.0.0
  read_pdf_text: ^0.3.1
  google_generative_ai: ^0.4.7
  http: ^1.2.0
  webview_flutter: ^4.7.0
  share_plus: ^7.2.2
  webview_flutter_android: ^4.10.11
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  syncfusion_flutter_pdf: ^24.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon_1024.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/icon/icon_1024.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_1024.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F5FAFD"
  adaptive_icon_foreground: "assets/icon/icon_1024.png"
